force-app/main/default/objects/StorageInformation__c/StorageInformation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains information about the org&#39;s storage limits</description>
    <label>StorageInformation</label>
</CustomObject>

force-app/main/default/objects/StorageInformation__c/fields/Data_Storage_Max__c.field-meta.xml
<CustomField>
    <fullName>Data_Storage_Max__c</fullName>
    <label>Data Storage Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StorageInformation__c/fields/Data_Storage_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Data_Storage_Remaining__c</fullName>
    <label>Data Storage Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StorageInformation__c/fields/File_Storage_Max__c.field-meta.xml
<CustomField>
    <fullName>File_Storage_Max__c</fullName>
    <label>File Storage Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StorageInformation__c/fields/File_Storage_Remaining__c.field-meta.xml
<CustomField>
    <fullName>File_Storage_Remaining__c</fullName>
    <label>File Storage Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Storage.cls
public with sharing class Storage {
    @AuraEnabled
    public static StorageInformation__c getStorage() {
        HttpRequest req = new HttpRequest();

        req.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.setHeader('Content-Type', 'application/json');
        req.setEndpoint('callout:REST_API/services/data/v48.0/limits/');
        req.setMethod('GET');
        
        // end of each request
        Http h = new Http();
        HttpResponse res = h.send(req);

        Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());

        Map<String, Object> dataStorage = (Map<String, Object>)m.get('DataStorageMB');
        Map<String, Object> fileStorage = (Map<String, Object>)m.get('FileStorageMB');

        StorageInformation__c storage = StorageInformation__c.getOrgDefaults();
        
        storage.Data_Storage_Max__c = Integer.valueOf(dataStorage.get('Max'));
        storage.Data_Storage_Remaining__c = Integer.valueOf(dataStorage.get('Remaining'));
        storage.File_Storage_Max__c = Integer.valueOf(fileStorage.get('Max'));
        storage.File_Storage_Remaining__c = Integer.valueOf(fileStorage.get('Remaining'));
        
        update storage;
        
        return storage;
    }
    
    @AuraEnabled
    public static StorageInformation__c getStorageInformation() {
        return StorageInformation__c.getOrgDefaults(); 
    }
}