force-app/main/default/objects/StorageInformation__c/StorageInformation__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains information about the org&#39;s storage limits</description>
    <label>StorageInformation</label>
</CustomObject>

force-app/main/default/objects/StorageInformation__c/fields/Data_Storage_Max__c.field-meta.xml
<CustomField>
    <fullName>Data_Storage_Max__c</fullName>
    <label>Data Storage Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StorageInformation__c/fields/Data_Storage_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Data_Storage_Remaining__c</fullName>
    <label>Data Storage Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StorageInformation__c/fields/File_Storage_Max__c.field-meta.xml
<CustomField>
    <fullName>File_Storage_Max__c</fullName>
    <label>File Storage Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StorageInformation__c/fields/File_Storage_Remaining__c.field-meta.xml
<CustomField>
    <fullName>File_Storage_Remaining__c</fullName>
    <label>File Storage Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StorageTest.cls
@isTest
private class StorageTest {
    public static testMethod void getStorage() {
        StorageInformation__c cs = new StorageInformation__c(
            Data_Storage_Max__c = 0,
            Data_Storage_Remaining__c = 0,
            File_Storage_Max__c = 0,
            File_Storage_Remaining__c = 0
        );
        insert cs;
        
        Test.startTest();
            SingleRequestMock StorageMock = new SingleRequestMock(200,'Complete','{"DataStorageMB":{"Max":5,"Remaining":2},"FileStorageMB":{"Max":20,"Remaining":2}}', null);
            Test.setMock(HttpCalloutMock.class, StorageMock); 
            cs = Storage.getStorage();
        Test.stopTest();

        cs = [SELECT Data_Storage_Max__c, Data_Storage_Remaining__c, File_Storage_Max__c, File_Storage_Remaining__c FROM StorageInformation__c LIMIT 1];
        System.assertEquals(5, cs.Data_Storage_Max__c);
        System.assertEquals(2, cs.Data_Storage_Remaining__c);
        System.assertEquals(20, cs.File_Storage_Max__c);
        System.assertEquals(2, cs.File_Storage_Remaining__c);
    }
}