force-app/main/default/objects/GitHub_User__c/GitHub_User__c.object-meta.xml
<CustomObject>
    <label>GitHub User</label>
    <nameField>
        <label>GitHub User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GitHub Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GitHub_User__c/fields/Is_Get_All_Repositories__c.field-meta.xml
<CustomField>
    <fullName>Is_Get_All_Repositories__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Get All Repositories?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GitHub_User__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/GitHubOwner__c.field-meta.xml
<CustomField>
    <fullName>GitHubOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>GitHub_User__c</referenceTo>
    <relationshipLabel>Repositories</relationshipLabel>
    <relationshipName>Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GitHubUserHandlerTest.cls
@isTest
public class GitHubUserHandlerTest {
    public static testMethod void getReposUsernameTest() {

        GitHub_User__c repoOwner = TestDataFactory.createGitHubUser('jfz94','14350484');
        repoOwner.Is_Get_All_Repositories__c = false;
        insert repoOwner;

        Test.startTest();
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('ReposMock');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json');
            Test.setMock(HttpCalloutMock.class, mock); 
            repoOwner.Is_Get_All_Repositories__c = true;
            update repoOwner;
        Test.stopTest();
        List<Repository__c> reps = [SELECT ID, GitHubOwner__c FROM Repository__c WHERE GitHubOwner__r.Login__c =: repoOwner.Login__c];

        System.assertNotEquals(0, reps.size());
        System.assertEquals(2, reps.size());
    }
}