force-app/main/default/objects/GitHub_User__c/GitHub_User__c.object-meta.xml
<CustomObject>
    <label>GitHub User</label>
    <nameField>
        <label>GitHub User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GitHub Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GitHub_User__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GitHub_User__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/GitHubOwner__c.field-meta.xml
<CustomField>
    <fullName>GitHubOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>GitHub_User__c</referenceTo>
    <relationshipLabel>Repositories</relationshipLabel>
    <relationshipName>Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/IsMonitored__c.field-meta.xml
<CustomField>
    <fullName>IsMonitored__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monitor?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Repository_Id__c.field-meta.xml
<CustomField>
    <fullName>Repository_Id__c</fullName>
    <label>Repository Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
global without sharing class  TestDataFactory {

    global static Repository__c createRepository(String repoName, String repoId, Boolean isMonitored, GitHub_User__c user){
        return new Repository__c(
            Name = repoName,
            Repository_Id__c = repoId,
            IsMonitored__c = isMonitored,
            GitHubOwner__c = user.Id
        );
    }

    global static GitHub_User__c createGitHubUser(String loginName, String externalId) {
        return new GitHub_User__c(
            Login__c = loginName,
            External_Id__c = externalId
        );
    }

    global static ContentVersion createContentVersion(String title,  String path, String version){
        return new ContentVersion(
            Title= title,
            PathOnClient = path + '.pdf',
            VersionData = EncodingUtil.base64Decode(version)
        );
    }
}