force-app/main/default/objects/GitHub_User__c/GitHub_User__c.object-meta.xml
<CustomObject>
    <label>GitHub User</label>
    <nameField>
        <label>GitHub User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GitHub Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GitHub_User__c/fields/Is_Get_All_Repositories__c.field-meta.xml
<CustomField>
    <fullName>Is_Get_All_Repositories__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Get All Repositories?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GitHub_User__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GitHubUserHandler.cls
public without sharing class GitHubUserHandler {

    public static List<GitHub_User__c> usersToGetRepositories  = new List<GitHub_User__c>();


    public GitHubUserHandler(){ 
    }

    public void onBeforeUpdate(List<GitHub_User__c> triggerOld , List<GitHub_User__c> triggerNew , Map<Id, GitHub_User__c> triggerOldMap , Map<Id, GitHub_User__c> triggerNewMap) {
        for(GitHub_User__c user : triggerNew) {
            if(Util.isChangedField(triggerNewMap.get(user.Id), triggerOldMap.get(user.Id),'Is_Get_All_Repositories__c') && user.Is_Get_All_Repositories__c == true) {
                usersToGetRepositories.add(user);
                user.Is_Get_All_Repositories__c = false;
            }
        }
    }

    public void onAfterUpdate(List<GitHub_User__c> triggerOld , List<GitHub_User__c> triggerNew , Map<Id, GitHub_User__c> triggerOldMap , Map<Id, GitHub_User__c> triggerNewMap) {
        if(!usersToGetRepositories.isEmpty()) {
            for(GitHub_User__c u : usersToGetRepositories) {
                GitHub.getRepos(u.Login__c);
            }
        }
    }

    
}