force-app/main/default/objects/Administrator__mdt/Administrator__mdt.object-meta.xml
<CustomObject>
    <label>Administrator</label>
    <pluralLabel>Administrators</pluralLabel>
</CustomObject>

force-app/main/default/objects/Administrator__mdt/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GitHub_User__c/GitHub_User__c.object-meta.xml
<CustomObject>
    <label>GitHub User</label>
    <nameField>
        <label>GitHub User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GitHub Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GetBranchInformationBatchTest.cls
@isTest
private class GetBranchInformationBatchTest {
    static testMethod void getBranchInformationBatch_Test() {
        GitHub_User__c repoOwner = TestDataFactory.createGitHubUser('jfz94', '14350484');
        insert repoOwner;

        insert TestDataFactory.createRepository('repoTest1','83738', true, repoOwner);

        Administrator__mdt admin = new Administrator__mdt(Email__c = 'test@gmail.com');

        Test.startTest();
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('BranchesMock');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json');
            Test.setMock(HttpCalloutMock.class, mock); 
            GetBranchInformationBatch batch = new GetBranchInformationBatch();
            Database.executeBatch(batch);
        Test.stopTest();
    }
}