force-app/main/default/objects/Administrator__mdt/Administrator__mdt.object-meta.xml
<CustomObject>
    <label>Administrator</label>
    <pluralLabel>Administrators</pluralLabel>
</CustomObject>

force-app/main/default/objects/Administrator__mdt/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Repository__c.field-meta.xml
<CustomField>
    <fullName>Repository__c</fullName>
    <label>Repository</label>
    <referenceTo>Repository__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GitHub_User__c/GitHub_User__c.object-meta.xml
<CustomObject>
    <label>GitHub User</label>
    <nameField>
        <label>GitHub User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GitHub Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GitHub_User__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GitHub_User__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/GitHubOwner__c.field-meta.xml
<CustomField>
    <fullName>GitHubOwner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>GitHub_User__c</referenceTo>
    <relationshipLabel>Repositories</relationshipLabel>
    <relationshipName>Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/IsMonitored__c.field-meta.xml
<CustomField>
    <fullName>IsMonitored__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Monitor?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Repository_Id__c.field-meta.xml
<CustomField>
    <fullName>Repository_Id__c</fullName>
    <label>Repository Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetBranchInformationBatch.cls
global class GetBranchInformationBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
	
    private String query; 
    global Integer recordsProcessed = 0;
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // getting the repositories which the user wants to monitor
		return Database.getQueryLocator('SELECT ID, Repository_Id__c, Name, GitHubOwner__r.Login__c  FROM Repository__c WHERE IsMonitored__c = true');
	}
    
    global void execute(Database.BatchableContext BC, List<Repository__c> scope) {
        List<Branch__c> allBranches = new List<Branch__c>();
        List<Branch__c> branches = new List<Branch__c>();

        for(Repository__c rep : scope) {
            // getting the branches of each repository
            branches = GitHub.getRepoBranches(rep.GitHubOwner__r.Login__c, rep.Name, rep.Repository_Id__c, false);
            // in case we have branches
            if(branches != null) {
                // we add them in a list to upsert them
                allBranches.addAll(branches);
            }
        }

        try{
            // upserting branches by external_id__c field
            Database.upsert(allBranches,GitHubService.getExternalFieldToUpdateRecords('External_Id__c', 'Branch__c'),false);
            recordsProcessed = allBranches.size();
        }catch(Exception e){
            System.debug('EXCEPTION UPSERTING BRANCHES: ' + e);
        }
    } 
    
    
    global void finish (Database.BatchableContext BC) {
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                JobItemsProcessed, ApexClassId, ApexClass.Name, 
                TotalJobItems, CreatedBy.Email
                FROM AsyncApexJob
                WHERE Id = :BC.getJobId()]; 
        
        List<String> emails = new List<String>();
        for (Administrator__mdt admin : [SELECT Email__c FROM Administrator__mdt]) {
            emails.add(admin.Email__c);
        }
        if(Limits.getEmailInvocations() + 1 < Limits.getLimitEmailInvocations() && !Test.isRunningTest()){
            Util.sendMessage(job, recordsProcessed, emails);
        }
        
        if(!Test.isRunningTest()){ 
            Database.executeBatch(new GetCommitsInformationBatch(), 100);
        }
    }
}