force-app/main/default/objects/Commit__c/Commit__c.object-meta.xml
<CustomObject>
    <label>Commit</label>
    <nameField>
        <displayFormat>CMT-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commit__c/fields/Repository__c.field-meta.xml
<CustomField>
    <fullName>Repository__c</fullName>
    <label>Repository</label>
    <referenceTo>Repository__c</referenceTo>
    <relationshipLabel>Commits</relationshipLabel>
    <relationshipName>Commits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GitHub_User__c/GitHub_User__c.object-meta.xml
<CustomObject>
    <label>GitHub User</label>
    <nameField>
        <label>GitHub User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GitHub Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GitHub_User__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Repository_Id__c.field-meta.xml
<CustomField>
    <fullName>Repository_Id__c</fullName>
    <label>Repository Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GitHubTest.cls
@isTest
private class GitHubTest {
    public static testMethod void getReposUsernameTest() {
        
        GitHub_User__c repoOwner = TestDataFactory.createGitHubUser('jfz94','14350484');
        insert repoOwner; 
        
    	Test.startTest();
        	StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('ReposMock');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json');
            Test.setMock(HttpCalloutMock.class, mock); 
        	GitHub.getRepos(repoOwner.Login__c);
        Test.stopTest();
        List<Repository__c> reps = [SELECT ID FROM Repository__c];
        System.assertEquals(2, reps.size());
    }
    
    public static testMethod void getRepoByNameTest() {
        Test.startTest();
        	StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('RepoByNameMock');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json');
            Test.setMock(HttpCalloutMock.class, mock); 
        	GitHub.getRepoByName('jfz94','jfz94.github.io');
        Test.stopTest();
            Repository__c rep = [SELECT Id, Description__c FROM Repository__c LIMIT 1];
            System.assertEquals('this is a description', rep.Description__c);
    }
    
    public static testMethod void searchRepoByNameTest() {
        Test.startTest();
        	StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('SearchRepoByNameMock');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json');
            Test.setMock(HttpCalloutMock.class, mock); 
        	GitHub.searchReposByName('github',1, null, 'interactions-asc');
        Test.stopTest();
            List<Repository__c> reps = [SELECT ID FROM Repository__c];
            System.assertEquals(1, reps.size());
    }

    public static testMethod void refreshCommitsTest() {

        GitHub_User__c repoOwner = TestDataFactory.createGitHubUser('jfz94','14350484');
        insert repoOwner;

        Repository__c rep = TestDataFactory.createRepository('jfz94.github.io','83738', true, repoOwner);
        insert rep;

        Test.startTest();
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource('CommitsMock');
            mock.setStatusCode(200);
            mock.setHeader('Content-Type', 'application/json');
            Test.setMock(HttpCalloutMock.class, mock); 

        	GitHub.getCommits('jfz94', 'jfz94.github.io', rep.Repository_Id__c, true);
        Test.stopTest();
        List<Commit__c> commits = [SELECT ID FROM Commit__c];
        System.assertEquals(2, commits.size());
    }
}